project_id = "tv-goldviewfx-local"

[api]
port = 55421
schemas = ["public", "storage", "auth"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 55422
shadow_port = 55420
major_version = 15

[studio]
port = 55423

[inbucket]
port = 55424

[analytics]
enabled = true
port = 55427
vector_port = 55428

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
jwt_expiry = 3600
enable_signup = false

[storage]
file_size_limit = "50MiB"

[edge_runtime]
policy = "per_worker"
